//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassMailer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassMailer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T1RUTwALAIAAAwAwQ0ZGIB7ggpUAAAC8AAB5P0dQT1NZnzqiAAB5/AAARihHU1VClJCY6AAAwCQAAAIwT1MvMonNF5QAAMJUAAAAYGNtYXBKoMkIAADCtAAAA8xoZWFkFbYPvAAAxoAAAAA2aGhlYQiuBPsAAMa4AAAAJGhtdHikADPXAADG3AAABkxtYXhwAZNQAAAAzSgAAAAGbmFtZUC/g28AAM0wAAADp3Bvc3T/uAAyAADQ2AAAACABAAQCAAEBAQ5IU0VTYW5zLUJsYWNrAAEBASf4EAD41AwA+NUC+NUD+BMER/vMHATf+qQFHAc0DxwIlBGkHHkmEgC7AgABAAUABwAOABUAHAAjACoAMQA3AD0AQwBJAE8AVQBbAGEAaABvAHkAgwCKAJEAlwCdAKQAqwCyALkAwADHAM4A1QDbAOEA6ADvAPUA+wEBAQcBDgEVARsBIQEoAS8BPAFJAU8BVQFcAWMBaQFvAXUBewGBAYcBjgGVAZoBnwGs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HSESans_Black {
            get {
                return ResourceManager.GetString("HSESans_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T1RUTwALAIAAAwAwQ0ZGIB7esLoAAAC8AAB9SkdQT1N+sJovAAB+CAAAMTZHU1VClJCY6AAAr0AAAAIwT1MvMofZF78AALFwAAAAYGNtYXBKoMkIAACx0AAAA8xoZWFkFO0PeAAAtZwAAAA2aGhlYQflBEsAALXUAAAAJGhtdHhRikGtAAC1+AAABkxtYXhwAZNQAAAAvEQAAAAGbmFtZU970kQAALxMAAADSHBvc3T/uAAyAAC/lAAAACABAAQCAAEBARBIU0VTYW5zLVJlZ3VsYXIAAQEBJvgQAPjUDAD41QL41gP4GARJ+8z6qPpeBRwHMA8cCJARrRx9KBIAvAIAAQAFAAcADgAVABwAIwAqADEANwA9AEMASQBPAFUAWwBhAGgAbwB5AIMAigCRAJcAnQCkAKsAsgC5AMAAxwDOANUA2wDhAOgA7wD1APsBAQEHAQ4BFQEbASEBKAEvATwBSQFPAVUBXAFjAWkBbwF1AXsBgQGHAY4BlQGaAZ8B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HSESans_Regular {
            get {
                return ResourceManager.GetString("HSESans_Regular", resourceCulture);
            }
        }
    }
}
